

stages:
  - build
  - package
  
java-build:
  # select the most appropriate image for your project
  image: maven:3.8-openjdk-11
  stage: build
  script:
    - mvn clean install -DskipTests=true
  artifacts:
    paths:
      - target/*.jar

docker-build:
  image: docker:latest
  services:
    - docker:dind
  stage: package
  script:
  - docker build -t myjava:latest .
  - docker login https://registry.hub.docker.com/ --username adityashitole456 --password-stdin Akansha@456
 # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - docker tag myjava:latest ibmcom/helloworld:latest
  - docker push ibmcom/helloworld:latest